#ifndef NEMINI_ERROR_H
#define NEMINI_ERROR_H

#include <SDL.h>

enum nemini_error {
    ERR_NONE,
    ERR_UNEXPECTED,

    // The following are generated by net.c:
    ERR_DNS_RESOLUTION,
    ERR_CONNECT,
    ERR_SSL_CTX_INIT,
    ERR_SSL_TLS_MIN_FAILED,
    ERR_SSL_CONNECT,
    ERR_SSL_CERT_MISSING,
    ERR_SSL_CERT_VERIFY,
    ERR_PUT_REQUEST,
    ERR_GET_HEADER,
    ERR_GET_BODY,
};

#endif
